# Generated by Django 4.2.17 on 2025-01-27 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('vehicle_type', models.CharField(choices=[('2W', '2-Wheeler'), ('4W', '4-Wheeler')], max_length=2)),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Visitor', 'Visitor'), ('Faculty', 'Faculty')], max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('vehicle_type', models.CharField(choices=[('2W', '2-Wheeler'), ('4W', '4-Wheeler')], max_length=2)),
                ('category', models.CharField(choices=[('Patient', 'Patient'), ('staff', 'staff'), ('VIP', 'VIP')], max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('booking_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('payment_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='openParkingSlot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('2W', '2-Wheeler'), ('4W', '4-Wheeler')], max_length=2)),
                ('category', models.CharField(choices=[('Regular', 'Regular'), ('VIP', 'VIP')], default='Regular', max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='registrationmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(default='waiting', max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
